# INVENTARIO DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-db
  template:
    metadata:
      labels:
        app: inventario-db
    spec:
      containers:
      - name: inventario-db
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: inventario
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: inventario_db
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -d
            - $(POSTGRES_DB)
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: inventario-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: inventario-data
        persistentVolumeClaim:
          claimName: inventario-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: inventario-db
spec:
  selector:
    app: inventario-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventario-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# INVENTARIO API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-api
  template:
    metadata:
      labels:
        app: inventario-api
    spec:
      containers:
      - name: inventario-api
        image: inventario-api:latest
        command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8001"]
        ports:
        - containerPort: 8001
        env:
        - name: DB_USER
          value: inventario
        - name: DB_PASSWORD
          value: postgres
        - name: DB_HOST
          value: inventario-db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: inventario_db
        - name: BROKER_HOST
          value: rabbitmq
        - name: RESERVE_ITEMS_TOPIC
          value: rpc_reserve_items
        livenessProbe:
          httpGet:
            path: /inventario/ping
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: inventario-api
spec:
  selector:
    app: inventario-api
  ports:
  - port: 8001
    targetPort: 8001